site_name: RCAC Documentation
site_description: Official RCAC documentation website.
site_url: https://docs.rcac.purdue.edu

theme:
  name: material
  logo: assets/purdue.png
  favicon: assets/purdue_favicon.png
  custom_dir: overrides
  font:
    text: Roboto
    code: Consolas
  features:
    - navigation.indexes
    # Back-to-top button
    - navigation.top
    - navigation.footer
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/js/tablefilter.js
  - assets/js/init-tablefilter.js
  - assets/js/breadcrumbs.js
  - assets/js/external-links.js

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      post_date_format: long
      categories_allowed:
        - Announcements
        - Anvil
        - Gautschi
        - Software
        - Slurm
        - Workflows
      pagination_per_page: 5
      pagination_if_single_page: true
  - tags:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
      # Do not include timestamp in the following pages
        - index.md
        - contact.md
        - blog/*
        - software/*
        - datasets/*
  - macros

nav:
  - HPC User Guides:
    - Anvil:
      - userguides/anvil/index.md
      - About:
        - Overview: userguides/anvil/overview.md
        - System Architecture: userguides/anvil/architecture.md
      - Access to Anvil: userguides/anvil/access.md
      - Getting Started: userguides/anvil/getting-started.md
      - Job Submission: userguides/anvil/jobs.md
      - File Management: userguides/anvil/file_management.md
      - Anvil Software: userguides/anvil/anvil-software.md
      - Help Desk: userguides/anvil/help.md
      - Anvil Composable Subsystem:
        - userguides/anvil/composable/index.md
        - Getting Started: userguides/anvil/composable/getting-started.md
        - Concepts: userguides/anvil/composable/concepts.md
        - Examples: userguides/anvil/composable/examples.md
      - Anvil Object Storage:
        - userguides/anvil/objectstorage/index.md
        - Getting Started: userguides/anvil/objectstorage/getting-started.md
        - Object Storage Concepts: userguides/anvil/objectstorage/concepts.md
        - Access: userguides/anvil/objectstorage/access.md
        - User Tools: userguides/anvil/objectstorage/usertools.md
        - Security and Access Control: userguides/anvil/objectstorage/acl.md
      - AnvilGPT (LLM): userguides/anvil/anvilgpt.md
      - Anvil Notebook: userguides/anvil/notebook.md
      - Maintenance Log: userguides/anvil/maintenance.md
      - Policies: userguides/anvil/policies.md
    - Gautschi:
      - userguides/gautschi/index.md
      - Gautschi Overview: userguides/gautschi/overview.md
      - Biography of Gautschi: userguides/gautschi/biography.md
      - Accounts: userguides/gautschi/accounts.md
      - Software: userguides/gautschi/software.md
      - Running Jobs: userguides/gautschi/run_jobs/index.md
      - File Storage and Transfer: userguides/gautschi/storage.md
      - Gateway (Open OnDemand): userguides/gautschi/gateway.md
      - Compiling Source Code: userguides/gautschi/compile.md
      - Frequently Asked Questions: userguides/gautschi/faq.md
      - Datasets: userguides/gautschi/datasets.md
    - Bell: https://www.rcac.purdue.edu/knowledge/bell
    - Gilbreth: https://www.rcac.purdue.edu/knowledge/gilbreth
    - Negishi: https://www.rcac.purdue.edu/knowledge/negishi
    - Scholar: https://www.rcac.purdue.edu/knowledge/scholar
    - Geddes: https://www.rcac.purdue.edu/knowledge/geddes
    - Hammer: https://www.rcac.purdue.edu/knowledge/hammer
    - Rossmann: https://www.rcac.purdue.edu/knowledge/rossmann
    - Weber: https://www.rcac.purdue.edu/knowledge/weber
  - Storage User Guides:
    - Data Depot: https://www.rcac.purdue.edu/knowledge/depot
    - Fortress: https://www.rcac.purdue.edu/knowledge/fortress
    - Scratch: https://www.rcac.purdue.edu/knowledge/scratch
    - Home Directory: https://www.rcac.purdue.edu/knowledge/home
    - REED Folder: https://www.rcac.purdue.edu/knowledge/reedfolder
    - Box Research Lab Folder: https://www.rcac.purdue.edu/knowledge/boxfolder
  - RCAC Resources:
    - RCAC Blogs:
      - blog/index.md
    - Software:
      - software/index.md
      - All Software: software/app_catalog.md
      - Compilers: software/compilers_catalog.md
      - MPIs: software/mpi_catalog.md
      - Computational Chemistry: software/chemistry_catalog.md
      - Fluid Dynamics: software/fluid_dynamics_catalog.md
      - Audio/Visualization: software/audio_visual_catalog.md
      - Library: software/library_catalog.md
      - Mathematics/Statistics: software/math_stat_catalog.md
      - Engineering: software/engineering_catalog.md
      - Geoscience: software/geoscience_catalog.md
      - Utilities: software/utilities_catalog.md
      - Workflow: software/workflow_catalog.md
    - Datasets:
      - datasets/index.md
      - AI: datasets/ai.md
      - Hydrological: datasets/hydrological.md
      - Meteorological: datasets/meteorological.md
      - Geospatial: datasets/geospatial.md
      - Covariates: datasets/Covariates.md
      - GeoAI: datasets/geoai.md
      - Igenomes: datasets/igenomes.md
    - RCAC Workshops:
      - workshops/index.md
      - HPC Exchange:
        - workshops/hpc_exchange/index.md
        - Week 1:
            - workshops/hpc_exchange/week1/index.md
            - Setting up: workshops/hpc_exchange/week1/setup.md
            - Access: workshops/hpc_exchange/week1/access.md
            - Unix: workshops/hpc_exchange/week1/unix.md
            - The Shell: workshops/hpc_exchange/week1/shell.md
            - Commands: workshops/hpc_exchange/week1/commands.md
            - Navigating Filesystems: workshops/hpc_exchange/week1/filesystem.md
            - Editing Files: workshops/hpc_exchange/week1/editing.md
            - Command Reference: workshops/hpc_exchange/week1/reference.md
        - Week 2:
            - workshops/hpc_exchange/week2/index.md
            - What is a Cluster?: workshops/hpc_exchange/week2/what-is-a-cluster.md
            - Purdue Clusters: workshops/hpc_exchange/week2/clusters.md
            - Cluster Access: workshops/hpc_exchange/eek2/access.md
            - Cluster Applications: workshops/hpc_exchange/week2/applications.md
            - Cluster Job Submission: workshops/hpc_exchange/week2/slurm-basics.md
            - File Storage and Transfer: workshops/hpc_exchange/week2/storage-transfer.md
        - Week 3:
            - workshops/hpc_exchange/week3/index.md
            - Scripting: workshops/hpc_exchange/week3/scripting.md

            - Pipes: workshops/hpc_exchange/week3/pipes.md
            - Managing processes: workshops/hpc_exchange/week3/processes.md
            - Files & directories: workshops/hpc_exchange/week3/files-directories.md
        - Week 4:
            - workshops/hpc_exchange/week4/index.md
            - Storage & transfers: workshops/hpc_exchange/week4/storage-transfer.md
            - Job history: workshops/hpc_exchange/week4/job-history.md
            - Utilization & monitoring: workshops/hpc_exchange/week4/utilization-monitoring.md
            - Workload management: workshops/hpc_exchange/week4/workload-management.md
            - Multinode & topology: workshops/hpc_exchange/week4/multinode-topology.md
      - Anvil Kubernetes: workshops/kubernetes-tutorial.md
      - Scientific Visualization with MatPlotLib:
        - workshops/matplotlib/index.md
        - Getting Started: workshops/matplotlib/introduction.md
        - Our First Script: workshops/matplotlib/first_script.md
        - The Second Script: workshops/matplotlib/sine_plot.md
        - Advanced Plotting: workshops/matplotlib/adv_plots.md
        - Types of Plots: workshops/matplotlib/plot_types.md
        - Colormaps: workshops/matplotlib/colormaps.md
        - Animations: workshops/matplotlib/animations.md
        - Envision Center: workshops/matplotlib/env_cent.md
  # - Tags: tags.md
  - Contact us: contact.md
  - FAQs: faq.md

extra:
  social:
  - icon: /fontawesome/regular/envelope
    name: Get additional help from rcac-help
    link: mailto:<rcac-help@purdue.edu>
  - icon: fontawesome/brands/github
    name: Check RCAC public GitHub page
    link: https://github.com/PurdueRCAC
  - icon: fontawesome/brands/x-twitter
    name: Follow RCAC on X
    link: https://x.com/PurdueRCAC
  - icon: fontawesome/brands/discord
    name: Join our Purdue RCD Community Discord channel
    link: https://discord.gg/RmtKZmaQW9
  - icon: /material/mailbox
    name: Contact Us
    link: /contact
  org: Rosen Center for Advanced Computing
  analytics:
    provider: google
    property: G-3D80JBWGP0  # Guangzhen's Google Analytics
    feedback:
      title: Page helpful? Submit your feedback if not.
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our <a href="https://github.com/PurdueRCAC/RCAC-Docs/issues/new?labels=feedback&title=[Feedback]:%20&body=>%20**Page%20Affected:**%20https://docs.rcac.purdue.edu{url}%0A>%20Please%20describe%20the%20issue%20you%20found%20on%20this%20page.%0A%0A" target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
# # Adding share buttons
# hooks:
#   - hooks/socialmedia.py

# Copyright
copyright: Copyright &copy; 2026 Rosen Center for Advanced Computing
