-- -*- lua -*-
-- Nextflow 25.10.4
-- Installed manually (non-Spack) to /apps/external/nextflow/25.10.4
-- Generated by deploy-nextflow.sh on 2026-04-17 19:14 UTC

whatis([[Name : nextflow]])
whatis([[Version : 25.10.4]])
whatis([[Short description : Data-driven computational pipelines (https://nextflow.io)]])

help([[Nextflow 25.10.4
Requires Java 17+. Loads openjdk/17.0.11_9 automatically.
Documentation: https://nextflow.io/docs/stable/
]])

depends_on("gcc/14.2.0")
depends_on("openjdk/17.0.11_9")

prepend_path("PATH", "/apps/external/nextflow/25.10.4/bin")
setenv("NEXTFLOW_HOME", "/apps/external/nextflow/25.10.4")
setenv("RCAC_NEXTFLOW_ROOT", "/apps/external/nextflow/25.10.4")
setenv("RCAC_NEXTFLOW_VERSION", "25.10.4")
